/* Authored English notes and Q&A for the eleven starter episodes.
   These are full translations; data, assumptions and source identities are unchanged. */
(function () {
  'use strict';
  const p = text => '<p>' + text + '</p>';
  D.i18n.pack('en', {
    label: 'EN',
    notes: {
      'persistent-objects': [
        p('Inside the illustrative cell are eight schematic RNA count marks. These are symbols, not a micrograph, actual molecular coordinates or experimental data. Each mark is created once and has a persistent identifier. The example demonstrates an authoring technique: retain visual objects when changing their representation so that the viewer can follow the connection. The number eight is specified by the COUNT constant in the episode file. The author of a scientific lesson must define its biological meaning separately.'),
        p('The same eight marks regroup into a row outside the cell drawing. This movement changes the representation of the measurement; it does not depict RNA leaving through the membrane and is not a model of a cellular process. The individual counts are now easier to enumerate. An animation like this must not substitute a different cell or set of observations without explicitly introducing the new object. The original cell remains on screen, and all eight marks retain their identities in the DOM.'),
        p('Each mark straightens into one segment of a single horizontal bar. On this illustrative scale, one count occupies 32 scene coordinate units, so the bar is 8 × 32 = 256 units long. Flat stroke ends preserve the exact length: rounded ends could visually add to the value. We have changed how the eight counts are displayed, but have not normalized the data or calculated a new biological quantity.'),
        p('Only the drawing scale changes now: each count is allocated 48 coordinate units instead of 32. Both the bar and its scale divisions expand. The value label remains eight. Magnification can make a small effect easier to read, but it must be distinguished from changing the source data, transforming values or changing measurement units. In a scientific lesson, the scale is specified explicitly and used consistently for all objects being compared.')
      ],
      'objects-to-distribution': [
        p('The scene contains sixteen illustrative observations. Their values are listed in the VALUES constant; none comes from a paper or experiment. Their initial positions are simply a convenient arrangement of the objects. Each circle has a persistent number. The next steps separate three operations: placing observations on a numerical scale, grouping them into intervals, and revealing the histogram outline. This lets the viewer see that a distribution describes a collection of observations, rather than a probability inside one object.'),
        p('Each circle now has a horizontal coordinate corresponding to its specified value on the scale from zero to ten. For now, vertical offsets only separate equal values and have no quantitative meaning. This is a dot display of the same sixteen observations. The scale divisions are fixed in advance, rather than adjusted to support a desired conclusion. If an observation outside the specified bins range is added, the component reports an error instead of silently removing it from the drawing.'),
        p('The same circles collect into intervals of width two: [0,2), [2,4), [4,6), [6,8) and [8,10]. The final right boundary is included. The counts are 1, 5, 5, 3 and 2, totaling sixteen. The vertical axis now measures the number of observations, as its label states. The objects first separate vertically, then align horizontally. Keeping the objects visible makes it possible to check that no observation has disappeared or been counted twice.'),
        p('Rectangles grow behind the circles. Each height is exactly the count in its interval, and the observations remain visible inside. This is a count histogram with equal bin widths, not a probability density plot. The component rejects unequal bin widths: that representation would require a separate definition of density and the meaning of area. The author must specify the values, boundary inclusion rules and scale before animating them. The component changes only the display geometry and does not recalculate the original values.')
      ],
      'replicates-and-means': [
        p('Here are two groups of three invented replicate measurements. Group A contains 4, 5 and 6, and group B contains 1, 5 and 9 arbitrary units. Initially they sit in rows so the lists can be read; row height does not yet represent value. This demonstrates a component, not an experimental result. In a real analysis, the author must specify what a replicate means: an independent sample, culture, animal or repeated measurement of the same material. These levels cannot automatically be treated as interchangeable.'),
        p('Every circle takes its height from the same scale, running from zero to ten. Horizontal offsets within a group merely separate the individual replicates and do not measure anything. The circles do not disappear when summary measures are introduced. Both groups use a fixed common scale: each must not be stretched independently to make a difference more striking. The component checks that every value lies within the specified domain and reports an error instead of silently clipping observations.'),
        p('A mean line appears at the arithmetic mean of each group: (4+5+6)/3 = 5 and (1+5+9)/3 = 5. It grows at the correct fixed height, rather than moving through misleading intermediate values. All six observations remain visible. The means are equal, but the individual measurements already show different spreads. These three illustrative replicates alone do not establish statistical significance, the robustness of an effect or the distribution of the whole population.'),
        p('Next to each group, a line extends from its smallest to its largest observation. In A, this is the range 4–6; in B, it is 1–9. This is the observed range, not a standard deviation, standard error or confidence interval. Naming the measure on screen prevents these quantities from being confused. A summary should supplement individual measurements rather than hide them. To show a different type of interval, the author must calculate and label that specific interval while keeping the common numerical scale.')
      ],
      'read-a-source': [
        p('This SVG was drawn specifically for the starter kit. It contains an invented dot plot and an illustrative matrix; it is not a figure from a scientific paper. The initial view shows the source as a whole. In a scientific lesson, it is replaced with the original image, with known dimensions, provenance and permitted use. The caption must clearly distinguish an illustrative diagram from published data. K.sourceWindow changes the viewing region while preserving the image’s proportions.'),
        p('The window moves to panel A. The image itself is not redrawn: the frame and viewing region change through the SVG viewBox. The requested crop is preserved exactly, and the inner window fits inside the available frame at the same aspect ratio. Spare space remains around the window; the plot is not stretched and neighboring panels are not added. Before using a real figure, check that axis labels, ticks, legends and panel identification remain intact. Magnification helps the viewer read the evidence, but must not remove inconvenient observations.'),
        p('We state an observation directly visible in the illustrative panel: the points in group B lie above those in group A on the displayed vertical scale. A contains 2, 3 and 4; B contains 6, 7 and 8 arbitrary units. This describes the six drawn values. It is not a conclusion about the entire population and does not establish statistical significance. The explanatory text sits separately from the source so that the viewer can compare the statement with what is actually shown.'),
        p('A limit on interpretation now appears separately: the figure alone does not establish why the groups differ. A causal conclusion requires information about the design, assignment of the intervention, possible confounding factors and repeated measurements. The observation remains on screen while this qualification is added. The template separates a description of the data from a proposed mechanism and avoids presenting a plausible story as a verified result. All values in this source remain explicitly illustrative.')
      ],
      'question-before-answer': [
        p('Initially, only two equal means of five are visible. The question should be asked before the individual values are revealed: can we conclude that the groups have the same spread? The question itself does not give away the correct answer. The buttons let the viewer request a hint or an answer at their own pace. This is an illustrative counterexample, not a statistical hypothesis test using experimental data.'),
        p('We reveal the same data specified in advance: A contains 4, 5 and 6; B contains 1, 5 and 9. Each point is one invented observation. Both groups use a common vertical scale from zero to ten. Their means remain at five; the data have not changed and were not chosen during the animation. The viewer can now check the initial prediction against the observations themselves.'),
        p('The hint suggests comparing the extreme values. The line for A runs from four to six, and the line for B runs from one to nine. These are the observed ranges of the two lists, not confidence intervals. Their lengths are two and eight, respectively. We show the comparison using the retained points before stating the answer in words.'),
        p('No: a mean alone does not determine spread or distribution. The two explicit lists are a sufficient counterexample to the claim that equal means imply identical distributions. This does not mean that three real observations can reliably reconstruct a population distribution. The question component stores the hint and answer disclosures separately; the author connects these states to the lesson steps and the accompanying drawing.')
      ],
      'sequence-and-pairs': [
        p('Eight illustrative symbols, A–H, are arranged in a row. The small number gives each symbol’s persistent index, and a line connects neighbors in sequence order. This is neither a sequence from a paper nor a predicted structure. The symbols are generic component elements: they could represent letters, positions, stages or other named objects. Their text and identifiers remain unchanged when the layout changes.'),
        p('The same row bends smoothly into an arc. No new symbols are created, and their order along the line does not change. The arc radius is calculated from the fixed length of the illustrative line; the episode author explicitly specifies the intermediate positions. This changes the geometry of the drawing and is not a physical simulation of molecular folding. The smooth movement helps the viewer follow each position by its number.'),
        p('Three relationships specified in advance are revealed: positions 1 and 8, 2 and 7, and 3 and 6. In the code, these are the index pairs 0–7, 1–6 and 2–5. The dashed lines denote exactly these pairs; proximity on the canvas does not automatically create a new relationship. The component accepts pairs as input and checks their indices, but does not infer them from the letters or know the rules of complementarity.'),
        p('Position 2 is selected: its outline, its partner at position 7 and their dashed connection are highlighted. Another letter can be selected by clicking or using Enter or Space; the arrow keys continue to navigate the lesson. The slider changes only the bend in the drawing. Indices, letters and specified relationships remain the same. This separates three things: the order of the objects, the selected relationships, and their positions on screen.')
      ],
      'matrix-identity': [
        p('This illustrative matrix has three rows and four columns. All twelve values are explicitly specified in VALUES and are not results from a scientific paper. The number and color in each cell refer to one pair of original indices, such as R3 and C2. The shared color scale is fixed from −2 to +2, with zero at its midpoint. The technique of retaining cells and labels comes from the CBIO7102 matrix scenes; their expression data, normalization procedures and clustering results have not been transferred here.'),
        p('Row R3 is selected. It shifts slightly to the right so the viewer can follow it. The dimmed neighboring rows have not changed their numerical values or color mapping: opacity indicates attention only. Matrix cell R3,C2 still contains +1. It is important to distinguish selecting an object, changing its screen position and numerically transforming the data. This step performs neither normalization nor a z-score calculation; it simply selects a row for the next movement.'),
        p('Row R3 becomes the first row. It first moves fully to the right into a free lane. R1 and R2 then shift downward while R3 rises to its new height; finally, R3 returns to the common grid. Its cells and label are not recreated. The order [R3,R1,R2] is specified by the ORDER constant. This demonstrates a permutation, not computed clustering: the component has no distance method, tree or scientific conclusion about the similarity of these rows. All twelve original numbers stay the same.'),
        p('The frame now narrows to the original pair R3,C2 in its new location. Its value is still +1, and the color mapping is unchanged. Reordering can help reveal structure or compare rows, but does not itself create a new quantity or establish a pattern. If the author of a scientific lesson wants to introduce a different normalization or color scale, that is a separate operation requiring its own explanation. This example shows only the preservation of identity, values and fixed color meaning during a permutation.')
      ],
      'partition-observations': [
        p('Here are twelve illustrative observations, S1–S12. Each circle represents exactly one observation; there are no hidden weights or rounded counts. This is a diagram for planning how data will be used, not paper data, new cells or model results. The idea of separating a reserve from the construction set comes from the CBIO7102 course-project presentation. In the reusable component, each source record has a persistent SVG object, and its role is determined by an explicit list of identifiers. Every subsequent step preserves the original set of twelve records.'),
        p('Four observations, S9–S12, are set aside in advance. The other eight remain available. Membership of the reserve is specified by identifiers, rather than chosen to produce an attractive result on screen. This is a visual diagram: it does not claim that the observations were obtained independently or from different biological samples. That depends on the experimental design. The component checks a narrower condition: each original identifier belongs to exactly one group, with nobody lost or counted twice.'),
        p('S1–S4 are selected for construction. S5–S8 are unused in this example; they remain visible so that the total can be checked. S9–S12 remain in reserve. We now have three disjoint groups of four observations. Moving the objects changes their roles and screen positions, but not their identities. No model is trained and no performance measure is computed here. The author of a scientific lesson must separately define what is constructed from the working group, how its size is chosen and why this partition suits the task.'),
        p('The reserve, S9–S12, now moves to the evaluation area. These are the same four records, not a new random sample. The working records S1–S4 remain separate, and S5–S8 are still unused. The diagram respects the stated boundary between construction and evaluation, but does not guarantee the absence of every kind of data leakage: shared donors, related samples, earlier tuning and repeated use of the test set require separate consideration. “Evaluation” names a data role; this component produces no metric and does not establish independence.')
      ],
      'prediction-amplitude': [
        p('There are four invented scalar measurements, S1–S4: 2, 4, 6 and 8 arbitrary units. A circle shows an observation, and a square shows the prediction for the same ID. They are separated vertically so both remain visible; only the horizontal coordinate encodes the numerical value. The initial predictions exactly match the observations, so Pearson correlation is 1 and L2 is 0. All four rows share a single scale from 0 to 12. There are no paper data, model training, control condition or hidden normalization here.'),
        p('Each original prediction is multiplied by 1.5, giving 3, 6, 9 and 12. The observations remain in their original positions; IDs and the horizontal scale do not change. Pearson correlation is still 1, although every prediction is too high. This is a property of centered Pearson correlation under positive scaling of a nonconstant series. L2 is now √30, approximately 5.48 arbitrary units. At every animation frame, the metrics are recalculated from the same current numbers that determine the squares’ positions, rather than from the eventual target values.'),
        p('The residual segments show four residuals: prediction minus observation. At an amplitude of 1.5, the residuals are +1, +2, +3 and +4 arbitrary units. Their squares sum to 1 + 4 + 9 + 16 = 30, so L2 is √30. This is the length of the overall error vector, not a mean error or RMSE: there is no division by the number of observations. Comparing different datasets requires attention to consistent units and numbers of observations. The color and segments explain an already computed metric; they add no new data.'),
        p('At amplitude 0, all four predictions are zero. Pearson correlation is undefined because the predictions have no spread; this state must not be described as a correlation of 0. L2 is √120, approximately 10.95 arbitrary units. The slider can set the amplitude anywhere from 0 to 1.5 again: at 1, individual values match and L2 becomes zero, while Pearson correlation remains 1 for every positive amplitude. The slider changes the author’s current multiplier; it does not estimate model parameters or demonstrate a model’s ability to generalize.')
      ],
      'resampling-means': [
        p('Here are six illustrative donors, D1–D6. The numbers 2, 3, 4, 6, 7 and 8 are invented after-minus-before changes for the individual donors, in arbitrary units. Horizontal position in the upper list indicates record order, not the size of the change; each value is written explicitly. These records already preserve the pairing of two measurements from the same donor. In a real paired bootstrap, the resampling unit remains the whole donor or that donor’s calculated difference. The component does not create the original measurements or assert that the donors are independent.'),
        p('The first supplied resample, B1, contains D1, D1, D2, D3, D4 and D6. Moving objects are copies of records; the original donors stay in place. Two positions refer to the same D1 and retain the same value, 2. This is allowed when sampling with replacement. A copy travels through a free lane, and its label appears after arrival so the movement does not cross the text. The list is explicitly specified in SAMPLES: replay uses the same list, and no random generation takes place here.'),
        p('The six copies converge into one new mean point: the arithmetic mean of B1. Its values give (2+2+3+4+6+8)/6 = 25/6, approximately 4.17. This is a summary of the resample, not a seventh donor. The original records remain above. The mean point’s horizontal position now encodes a number on the fixed 0–10 scale, in the same arbitrary units. The convergence of the copied objects represents calculating a mean: their individual values do not change or become equal to that mean.'),
        p('The operation is repeated for five more lists specified in advance. All six mean points use the same scale. Their means are B1 = 25/6, B2 = 5, B3 = 6, B4 = 19/6, B5 = 20/3 and B6 = 11/3. This is a small illustrative set of resamples, not a sufficient numerical procedure for estimating an interval. The component reports neither confidence limits nor a p-value. A real analysis must separately justify the resampling unit and the dependency structure; a large number of copies does not replace new independent biological samples.')
      ],
      'threshold-ranking': [
        p('Here are six invented cases with known true classes. Cases A, C and E are positive; cases B, D and F are negative. Each letter preserves the identity of a case. Its horizontal coordinate represents a score on a fixed scale from 0 to 1. This is a ranking number, not necessarily a probability. The selection rule is score greater than or equal to the threshold. At the initial threshold of 0.95, nobody is selected. Precision is undefined for an empty selection; recall is zero because none of the three positive cases has been found yet. The slider is available immediately.'),
        p('The threshold falls to 0.8. A, with score 0.9, and B, with score 0.8, enter the selection: equality with the threshold is included in the rule. Two cases are selected, and one is truly positive. Precision is 1/2; recall is 1/3 because there are three positive cases in total. These ratios answer different questions: how many selected cases are correct, and how many true positives have been found? The point on the right is calculated from the same integer counts. As the threshold moves, counts change only when it crosses observations; fractional cases never appear.'),
        p('At threshold 0.6, C and D enter together. Their scores are equal, so the order of the letters must not artificially change the result. Four cases are now selected: two true positives and two false positives. Precision remains 2/4 = 0.5, while recall increases to 2/3. The PR path consists of horizontal and vertical segments; diagonal interpolation is not used. Lowering the threshold does not necessarily increase precision: the next case could be either positive or negative. The scores and true classes themselves do not change.'),
        p('The threshold first passes all remaining scores, and then the area rectangles appear. Each rectangle’s height is the precision after the next group of equal scores is included; its width is the increase in recall. In this illustrative dataset, average precision is (1/3)×1 + (1/3)×0.5 + (1/3)×0.6 = 0.70. Negative cases that do not increase recall contribute zero width. AP describes the whole ranking; it is not the precision at the final point, which here is 3/6 = 0.5. The name AUPRC can refer to other integration conventions, including trapezoids: this example specifically shows discrete average precision. All values are synthetic.')
      ]
    },
    qa: {
      'persistent-objects': [
        { q: 'Did the value change when the bar grew?', a: p('No. In the final step, the drawing scale changes together with the axis divisions. The value remains eight. Normalization or a data transformation would be a separate operation.'), source: 'Illustrative example: eight schematic counts' },
        { q: 'Does this animate RNA leaving the cell?', a: p('No. The symbols regroup so they can be counted. Their movement explains how the measurement is displayed, not a cellular process.'), source: 'Explanation of the illustrative diagram' }
      ],
      'objects-to-distribution': [
        { q: 'What does a bar’s height mean?', a: p('The number of supplied observations in that interval. All intervals in the example have equal widths. The sum of the heights equals the number of observations.'), source: 'Illustrative values in this episode' },
        { q: 'Do the data change if different intervals are chosen?', a: p('The numbers themselves stay the same, but their grouping and the histogram’s appearance change. A different grouping must not be mistaken for a change in a biological process.'), source: 'Explanation of a histogram' }
      ],
      'replicates-and-means': [
        { q: 'Is the range line a confidence interval?', a: p('It shows the minimum and maximum observed values. This is a range, not a confidence interval, standard deviation or standard error.'), source: 'Definition of the measure used in this example' },
        { q: 'Why is showing two means not enough?', a: p('Both groups have a mean of 5, but the sets 4, 5, 6 and 1, 5, 9 differ substantially. Individual points show a difference that the mean hides.'), source: 'Invented gallery values' }
      ],
      'read-a-source': [
        { q: 'Is this an actual figure from a paper?', a: p('No. The SVG was created specifically for the library and contains invented values. In a new lesson, replace it with a verified source or retain an explicit label identifying it as an illustrative diagram.'), source: 'The library’s original illustrative SVG' },
        { q: 'Do the higher B points explain why the groups differ?', a: p('The figure shows a difference between six values. A causal explanation requires information about the experimental design and additional evidence; the positions of the points are not enough.'), source: 'Limits on interpreting the illustrative figure' }
      ],
      'question-before-answer': [
        { q: 'What exactly does this example demonstrate?', a: 'Two specific lists can have a mean of 5 and different ranges. Therefore, the mean does not determine every property of a list.', source: 'Illustrative data: A = [4, 5, 6], B = [1, 5, 9]; direct arithmetic.' },
        { q: 'Is the length of the displayed line the uncertainty of the mean?', a: 'No. It connects the smallest and largest observations. A confidence interval for the mean would require a different procedure and a separate justification.', source: 'Definition of the range, max − min; no confidence intervals are calculated in this example.' }
      ],
      'sequence-and-pairs': [
        { q: 'Do pairs arise because symbols are close together in the drawing?', a: 'No. The author explicitly supplies the list of pairs, and the layout only displays it. Changing coordinates does not recalculate the pairs.', source: 'Illustrative diagram: 1↔8, 2↔7, 3↔6; no biological model is used here.' },
        { q: 'Can the arc be treated as a predicted RNA structure?', a: 'No. A–H are illustrative symbols, and the arc is calculated for a visual explanation. A scientific structure requires separate data or an explicitly identified model.', source: 'Geometric example of K.sequenceTrack; no paper data are used.' }
      ],
      'matrix-identity': [
        { q: 'Did the value in R3,C2 change after reordering?', a: 'No. It is still +1. The same cell moved; its number and color mapping did not change.', source: 'The illustrative VALUES matrix in episode 7; persistent indices in K.heatmap.' },
        { q: 'Does this permutation establish similarity or clustering between rows?', a: 'No. The author supplied the order [R3, R1, R2]. The component displays the permutation and does not compute distances or clusters.', source: 'The explicit ORDER constant and the K.heatmap.setOrder contract.' }
      ],
      'partition-observations': [
        { q: 'Which observations are used for evaluation, and were they in the working group?', a: 'S9–S12. In this explicit diagram, they are set aside in advance and do not belong to the construction group S1–S4.', source: 'The illustrative RESERVED, BUILD and TESTING lists in episode 8.' },
        { q: 'Do disjoint lists automatically imply statistical independence?', a: 'No. The component checks only identifiers and roles. Independence depends on the experimental design and the relationships between observations.', source: 'The K.partitionActors contract: membership validation, not a probability model.' }
      ],
      'prediction-amplitude': [
        { q: 'Why is Pearson correlation 1 when predictions are 1.5 times the observations?', a: 'Pearson correlation compares deviations from the mean after dividing by their lengths. A common positive multiplier cancels. Here the observations are [2, 4, 6, 8] and the predictions are [3, 6, 9, 12]: the relationship is linear, but the individual values do not match.', source: 'Illustrative ITEMS values in episode 9; the centered Pearson formula in K.predictionComparison.' },
        { q: 'What does L2 mean, and why is Pearson correlation undefined at zero amplitude?', a: 'L2 is the square root of the sum of the squared prediction-minus-observation differences for the four cases. At amplitude 1.5, it is √30 ≈ 5.48; at zero, it is √120 ≈ 10.95. A constant prediction has zero spread, making the denominator of Pearson correlation zero. We therefore display “undefined”, not 0.', source: 'The same four illustrative observations; direct calculation of residual differences, without statistical inference.' }
      ],
      'resampling-means': [
        { q: 'Why does D1 occur twice in the first resample?', a: 'This is sampling with replacement. The first record is selected twice and contributes twice to the mean. The copies share sourceId D1 but have different slot numbers. This does not create new donors.', source: 'The explicit B1 list: D1, D1, D2, D3, D4, D6; all data are illustrative.' },
        { q: 'How can a bootstrap preserve paired measurements?', a: 'First calculate the after-minus-before change within each donor, then sample whole donor records with replacement. Alternatively, carry both values together under one ID. Resampling the two conditions independently destroys the pairing. The six displayed means are not a confidence interval.', source: 'Recipe for preserving the resampling unit; the helper receives differences already calculated and lists already specified.' }
      ],
      'threshold-ranking': [
        { q: 'Why do C and D enter together?', a: 'Both scores are 0.6. Under the rule score ≥ threshold, a threshold of 0.6 includes both cases, regardless of their order in the array.', source: 'Illustrative cases C and D in DATA; the explicit K.binaryRanking.at rule.' },
        { q: 'Does AP = 0.70 mean 70% precision at the selected threshold?', a: 'No. AP sums increases in recall weighted by the precision after each score group. When all six cases are selected, precision is 3/6 = 0.5, although AP for this ranking is 0.70.', source: 'Direct calculation for six invented cases; discrete average precision.' }
      ]
    }
  });
})();
