/* Three different compositions with invented, hand-checkable biology data. */
(function(){
'use strict';
function tr(ru,en){D.i18n.pack('en',{strings:{[ru]:en}});return ru;}
function words(parent,id,x,y,width,height,ru,en,size=23,color=C.white){return L.textBox(parent,{id,x,y,width,height,text:tr(ru,en),size,color,padding:3,align:'center',valign:'middle'});}
const SOURCE=tr('Учебные числа · методы: OSCA, Scanpy, OpenStax','Teaching numbers · methods: OSCA, Scanpy, OpenStax');
function register(id,title,notes,qa,url,build){D.i18n.pack('en',{notes:{[id]:notes.map(n=>F.note(n[1]))},qa:{[id]:[{q:qa[0][1],a:qa[1][1],source:'Illustrative fixture; method reference',url}]}});D.deck.register({id,title:tr(...title),chapter:tr('Биологические операции','Biological operations'),notes:notes.map(n=>F.note(n[0])),qa:[{q:qa[0][0],a:qa[1][0],source:'Учебные числа; источник метода',url}],build});}
function sync(control,value){control.input.value=String(value);control.output.textContent=String(+value.toFixed(2));}
function slider(ctx,root,label,min,max,value,step,onChange){const control=T.control(root,label,min,max,value,step,onChange,340,544,600);L.contract(control.el,{id:'biology-control',space:root,box:{x:330,y:536,width:620,height:76},measure:'element'});return control;}
const CELLS=[['c1','D1','T',1,3],['c5','D2','T',4,2],['c3','D1','B',5,0],['c7','D2','B',2,2],['c2','D1','T',2,4],['c6','D2','T',0,4],['c4','D1','B',3,2],['c8','D2','B',6,0]].map(([id,sample,stratum,...counts])=>({id,sample,stratum,counts}));
register('bio-pseudobulk',['Клетки складываются внутри донора','Sum cells within each donor'],[
 ['Восемь придуманных клеток имеют два гена G1,G2. D1 и D2 — два предполагаемо независимых донора; T и B обозначают два типа клеток. Числа в скобках — исходные отсчёты, не нормированные значения.','Eight invented cells have two genes G1,G2. D1 and D2 are assumed independent donors; T and B are two cell types. Brackets show raw counts, not normalized values.'],
 ['Сохраняем каждую клетку и группируем по паре донор × тип клетки. Четыре профиля принадлежат двум донорам. Число клеток не становится числом независимых биологических повторов.','Keep every cell and group by donor × cell type. Four profiles belong to two donors. The cell count does not become the number of independent biological replicates.'],
 ['Суммируем исходные отсчёты каждого гена: D1/T=[3,7], D1/B=[8,2], D2/T=[4,6], D2/B=[8,2]. Список исходных клеток сохраняется в каждом профиле. Итоги G1=23,G2=17; 8 клеток, 4 профиля, 2 донора. Ползунок заново собирает суммы. Этот набор не обосновывает анализ различий условий.','Sum each gene’s raw counts: D1/T=[3,7], D1/B=[8,2], D2/T=[4,6], D2/B=[8,2]. Every profile retains its source cell IDs. Totals are G1=23,G2=17; 8 cells, 4 profiles, 2 donors. The slider rebuilds the sums. This fixture does not support differential expression between conditions.']
 ],[['Четыре профиля означают четыре независимых донора?','Do four profiles mean four independent donors?'],['Нет. На каждый из двух доноров приходится два типа клеток. Независимость определяется дизайном; здесь предполагаются два независимых донора, по два в каждом типе.','No. Each of the two donors contributes two cell types. Independence comes from the design; this example assumes two independent donors, two represented in each type.']],
 'https://bioconductor.org/books/release/OSCA.multisample/multi-sample-comparisons.html',ctx=>{
 const v=F.stage(ctx,tr('Клетки складываются внутри донора','Sum cells within each donor'),'',SOURCE),stage=K.viewport(v.svg),chart=K.countAggregation(stage,{cells:CELLS,genes:['G1','G2'],frame:{x:90,y:250,width:1100,height:270}}),state={group:0,sum:0};
 const left=words(stage,'bio-pb-input',80,147,330,78,'Клетка · донор / тип\n[G1, G2] — отсчёты','Cell · donor / type\n[G1, G2] — raw counts',22);
 const right=words(stage,'bio-pb-output',730,147,460,78,'Сумма по донору × типу\nШкала полос: 0–8 отсчётов','Sum within donor × type\nBar scale: 0–8 counts',22);
 words(stage,'bio-pb-n',120,486,1040,45,'8 клеток → 4 профиля; независимых доноров n = 2','8 cells → 4 profiles; independent donors n = 2',24);
 function paint(){chart.setProgress(state);sync(control,state.sum);F.opacity(left.el,1-state.group*.6);F.opacity(right.el,state.group);v.caption(state.sum===1?tr('Суммы G1 = 23, G2 = 17. Каждый профиль хранит свои исходные клетки.','Totals G1 = 23, G2 = 17. Every profile retains its source cells.'):state.group===1?tr('Складываем отсчёты G1 и G2. Доноры и типы остаются раздельными.','Add the G1 and G2 counts. Donors and cell types stay separate.'):tr('Следите за ID: группировка меняет расположение, но сохраняет клетку.','Follow the IDs: grouping changes position while preserving each cell.'));}
 const driver=F.driver(state,paint);ctx.onDispose(driver.dispose);const control=slider(ctx,v.root,tr('Собрать сумму','Assemble the sum'),0,1,0,.01,value=>driver.set({group:1,sum:value}));
 paint();ctx.step(()=>driver.to({group:1},{duration:2300}));ctx.step(()=>driver.to({sum:1},{duration:2500}));return v.root;
 });
const ROWS=[{id:'c1',counts:[1,3]},{id:'c2',counts:[2,6]},{id:'c3',counts:[4,4]}];
register('bio-normalize',['Сначала общий итог, затем log1p','First a common total, then log1p'],[
 ['Три клетки имеют исходные отсчёты [1,3], [2,6], [4,4]. Их полные итоги равны 4,8,8. Все гены этой маленькой матрицы включены. Исходные значения постоянно остаются слева.','Three cells have raw counts [1,3], [2,6], [4,4]. Their full totals are 4,8,8. Every gene in this tiny matrix is included. Raw values remain visible on the left.'],
 ['При целевом итоге 8 множители равны 2,1,1. Нормированные строки [2,6], [2,6], [4,4] имеют одинаковую сумму. Значения стали относительными к выбранному итогу; это не новые наблюдаемые молекулы. Ползунок меняет целевой итог, не исходные отсчёты.','At target total 8, multipliers are 2,1,1. Normalized rows [2,6], [2,6], [4,4] have the same sum. Values are relative to the chosen total; they are not newly observed molecules. The slider changes the target total, not the raw counts.'],
 ['Только после нормировки применяем натуральный log1p: ln(1+x). При итоге 8 получаем [ln3,ln7], [ln3,ln7], [ln5,ln5]. После логарифмирования суммы строк обычно различаются. У каждого столбца своя явно указанная шкала. Ноль остаётся нулём и не доказывает отсутствие гена; строка с нулевым итогом отклоняется моделью.','Only after normalization apply natural log1p: ln(1+x). At total 8 this gives [ln3,ln7], [ln3,ln7], [ln5,ln5]. Row sums generally differ after logging. Every column has its own explicit scale. Zero remains zero and does not prove gene absence; the model rejects a row with zero total.']
 ],[['Почему две первые клетки стали одинаковыми?','Why do the first two cells become equal?'],['Их исходные соотношения G1:G2 одинаковы, 1:3. Нормировка на общий итог сохраняет доли и убирает различие общих итогов; она не доказывает биологическое равенство клеток.','Their raw G1:G2 ratio is the same, 1:3. A common total preserves proportions and removes the total-size difference; it does not establish biological equality of the cells.']],
 'https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.normalize_total.html',ctx=>{
 const v=F.stage(ctx,tr('Сначала общий итог, затем log1p','First a common total, then log1p'),'',SOURCE),stage=K.viewport(v.svg),chart=K.countNormalization(stage,{rows:ROWS,targetTotal:8,maxTotal:16}),state={targetTotal:8,normalize:0,log:0};
 words(stage,'bio-norm-raw',80,150,330,80,'Исходные отсчёты\nШкала 0–6','Raw counts\nScale 0–6',23);
 words(stage,'bio-norm-scaled',433,150,330,80,'На общий итог\nШкала 0–16','Scale to a common total\nScale 0–16',23);
 words(stage,'bio-norm-log',796,150,380,80,'ln(1 + нормированное)\nШкала 0–ln17 ≈ 2,83','ln(1 + normalized)\nScale 0–ln17 ≈ 2.83',23);
 words(stage,'bio-norm-genes',80,478,245,52,'G1, G2 — сверху вниз','G1, G2 — top to bottom',20);
 const detail=words(stage,'bio-norm-detail',330,478,860,52,'Целевой итог = 8; множители: 2, 1, 1','Target total = 8; multipliers: 2, 1, 1',24);
 function paint(){chart.setState(state);sync(control,state.targetTotal);const total=state.targetTotal.toFixed(0),factors=chart.model().rows.map(r=>r.factor.toFixed(2)).join(' · ');detail.setText(tr('Целевой итог = '+total+'; множители: '+factors,'Target total = '+total+'; multipliers: '+factors));v.caption(state.log>0?tr('log1p меняет значения. Общий итог после него не сохраняется.','log1p changes the values. The common total does not remain after it.'):state.normalize>0?tr('Умножаем каждый ген клетки на целевой итог / исходный итог.','Multiply every gene in a cell by target total / raw total.'):tr('Слева остаются измерения; два преобразования имеют отдельные шкалы.','Measurements stay on the left; the two transformations have separate scales.'));}
 const driver=F.driver(state,paint);ctx.onDispose(driver.dispose);const control=slider(ctx,v.root,tr('Целевой итог','Target total'),1,16,8,1,value=>driver.set({targetTotal:value,normalize:1,log:state.log}));paint();ctx.step(()=>driver.to({normalize:1},{duration:2100}));ctx.step(()=>driver.to({normalize:1,log:1},{duration:2200}));return v.root;
 });
register('bio-alleles',['Две копии на один диплоид','Two copies per diploid'],[
 ['Учебная выборка: 10 полностью генотипированных аутосомных диплоидов, AA=4, Aa=4, aa=2. Слева постоянно видны наблюдаемые частоты генотипов 0,4;0,4;0,2. Два маленьких маркера на особь обозначают две аллельные копии.','Teaching sample: 10 completely genotyped autosomal diploids, AA=4, Aa=4, aa=2. Observed genotype frequencies 0.4,0.4,0.2 remain visible on the left. Two small marks per individual denote two allele copies.'],
 ['Группируем копии по аллелю: A=2×4+4=12, a=2×2+4=8. Знаменатель теперь 20 копий; p=0,6,q=0,4. Это прямой подсчёт без предположения Харди–Вайнберга. Маркеры сохраняют исходный генотип и номер особи.','Group copies by allele: A=2×4+4=12, a=2×2+4=8. The denominator is now 20 copies; p=0.6,q=0.4. This is direct counting without a Hardy–Weinberg assumption. Marks retain their source genotype and individual index.'],
 ['Отдельная модель независимого случайного объединения гамет даёт p²,2pq,q² = 0,36;0,48;0,16. Ожидаемые числа 3,6;4,8;1,6 не являются наблюдаемыми особями. Равновесие между поколениями дополнительно предполагает отсутствие отбора, мутации и миграции и пренебрежимо малый дрейф. Здесь нет теста равновесия или вывода о популяции.','A separate model of independent random gamete union gives p²,2pq,q² = 0.36,0.48,0.16. Expected counts 3.6,4.8,1.6 are not observed individuals. Equilibrium across generations additionally assumes no selection, mutation or migration and negligible drift. This is not an equilibrium test or a population inference.']
 ],[['Нужно ли равновесие Харди–Вайнберга, чтобы посчитать p?','Is Hardy–Weinberg equilibrium needed to count p?'],['Нет. При полных диплоидных генотипах p=(2AA+Aa)/(2n). Равновесная формула относится к отдельным ожидаемым частотам генотипов, не к подсчёту аллелей.','No. With complete diploid genotypes, p=(2AA+Aa)/(2n). The equilibrium formula concerns separate expected genotype frequencies, not allele counting.']],
 'https://openstax.org/books/biology-2e/pages/19-1-population-evolution',ctx=>{
 const v=F.stage(ctx,tr('Две копии на один диплоид','Two copies per diploid'),'',SOURCE),stage=K.viewport(v.svg),chart=K.alleleFrequency(stage,{counts:{AA:4,Aa:4,aa:2}}),state={count:0,expect:0};
 words(stage,'bio-genotype-title',80,153,345,80,'Наблюдаемые генотипы\nЧастота: 0–1; n = 10','Observed genotypes\nFrequency: 0–1; n = 10',22);
 words(stage,'bio-allele-title',467,153,390,80,'Копии A и a\nВсего 2n = 20','A and a copies\nTotal 2n = 20',22);
 words(stage,'bio-hwe-title',935,153,255,80,'Ожидается при HWE\nЧастота: 0–1','Expected under HWE\nFrequency: 0–1',22,C.gold);
 words(stage,'bio-hwe-condition',110,485,1060,46,'HWE: независимое случайное объединение гамет; это ожидание модели','HWE: independent random gamete union; this is a model expectation',23);
 function paint(){chart.setProgress(state);sync(control,state.count+state.expect);v.caption(state.expect>0?tr('p² = 0,36; 2pq = 0,48; q² = 0,16. Наблюдения слева не меняются.','p² = 0.36; 2pq = 0.48; q² = 0.16. Observations on the left do not change.'):state.count===1?tr('A: 12/20 = 0,6; a: 8/20 = 0,4. Подсчёт не требует HWE.','A: 12/20 = 0.6; a: 8/20 = 0.4. Counting does not require HWE.'):tr('Две копии каждой особи сохраняют связь с её исходным генотипом.','Each individual’s two copies retain their original genotype link.'));}
 const driver=F.driver(state,paint);ctx.onDispose(driver.dispose);const control=slider(ctx,v.root,tr('Подсчёт → ожидание','Count → expectation'),0,2,0,.01,value=>driver.set({count:Math.min(1,value),expect:Math.max(0,value-1)}));paint();ctx.step(()=>driver.to({count:1},{duration:2300}));ctx.step(async()=>{if(state.count<1){const result=await driver.to({count:1},{duration:1300});if(!result.completed)return result;}return driver.to({expect:1},{duration:2100});});return v.root;
 });
})();
