'use strict';const Q=require('./lib.cjs');
Q.run('interaction',async ctx=>{const{page}=ctx;ctx.testedModes=[];
 async function check(name,fn){const ok=!!(await fn());ctx.checks.push({name,ok});if(!ok)throw Error('Failed: '+name);}
 await page.evaluate(()=>{D.i18n.setLang('ru');D.appearance.set({font:'sans',background:'black',palette:'ocean'});D.deck.show(0,0);});
 await page.locator('[data-action="next"]').click();await page.waitForFunction(()=>!D.deck.current().busy);await check('Next advances a step',()=>page.evaluate(()=>D.deck.current().step===1));
 await page.locator('[data-action="prev"]').click();await page.waitForFunction(()=>!D.deck.current().busy);await check('Previous returns to the initial state',()=>page.evaluate(()=>D.deck.current().step===0));
 await page.evaluate(()=>{window.__rnaInteractionRoot=D.deck.root();window.__rnaInteractionActors=[...D.deck.root().querySelectorAll('svg path,svg circle,svg line')];});await page.keyboard.press('ArrowRight');await page.waitForTimeout(300);await page.keyboard.press('l');await check('Language switches during motion without replacing actors',()=>page.evaluate(()=>D.i18n.lang()==='en'&&D.deck.root()===__rnaInteractionRoot&&__rnaInteractionActors.every(n=>n.isConnected)));await page.waitForFunction(()=>!D.deck.current().busy);await check('Motion completes after the language change',()=>page.evaluate(()=>D.deck.current().step===1&&D.deck.root()===__rnaInteractionRoot));
 await page.locator('[data-action="reading"]').click();await check('Notes open',()=>page.locator('#notes').evaluate(n=>!n.inert));await page.locator('[data-action="questions"]').click();await check('Scene questions exist',()=>page.locator('.qa-item').count().then(n=>n>0));const answer=page.locator('.qa-item').first(),summary=answer.locator('summary');const before=await answer.evaluate(n=>n.open);await summary.click();await check('Answer toggles',()=>answer.evaluate((n,b)=>n.open!==b,before));if(!await answer.evaluate(n=>n.open))await summary.click();await page.locator('#readingLanguageToggle').click();await check('Open answer survives a language change',()=>answer.evaluate(n=>n.open));
 await page.evaluate(()=>D.i18n.setLang('ru'));await page.locator('[data-action="guide"]').click();await page.locator('#qaSearch').fill('псевдо');await check('Study guide searches RNA questions',()=>page.locator('.qa-scene-group').count().then(n=>n>0));await page.locator('.qa-scene-jump').first().click();await page.locator('[data-action="close-reading"]').click();
 await page.locator('[data-action="overview"]').click();await check('Overview lists every scene',()=>page.locator('#overviewGrid button').count().then(n=>n===ctx.scenes.length));await page.locator('[data-action="close-overview"]').click();
 await page.locator('[data-action="more"]').click();if(!await page.locator('#appearanceSettings').evaluate(n=>n.open))await page.locator('#appearanceSettings summary').click();await page.locator('#appearanceBackground').selectOption('white');await page.locator('#appearancePalette').selectOption('botanical');await page.locator('#appearanceFont').selectOption('serif');await check('Appearance controls update background, palette and font',()=>page.evaluate(()=>{const a=D.appearance.get();return a.background==='white'&&a.palette==='botanical'&&a.font==='serif';}));await page.locator('[data-action="more"]').click();
 await page.evaluate(()=>{D.i18n.setLang('ru');D.appearance.set({background:'black',palette:'ocean',font:'sans'});D.deck.show(0,0);window.__rnaCancelledRoot=D.deck.root();D.deck.next();});await page.waitForTimeout(250);await page.keyboard.press('End');await page.evaluate(()=>window.__rnaCancelledHTML=__rnaCancelledRoot.outerHTML);await page.waitForTimeout(2400);await check('Leaving a moving scene cancels stale writes',()=>page.evaluate(()=>D.deck.current().index===D.deck.count()-1&&D.deck.root().dataset.rnaScene==='rna-takeaways'&&!__rnaCancelledRoot.isConnected&&__rnaCancelledRoot.outerHTML===__rnaCancelledHTML));
 for(const[w,h]of[[960,600],[844,390]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(100);await check(`Five controls fit ${w}×${h}`,()=>page.locator('.chrome > button').evaluateAll((nodes,{w,h})=>nodes.length===5&&nodes.every(n=>{const r=n.getBoundingClientRect();return r.left>=0&&r.right<=w+1&&r.top>=0&&r.bottom<=h+1;}),{w,h}));await page.locator('[data-action="reading"]').click();await check(`Notes open at ${w}×${h}`,()=>page.locator('#notes').evaluate(n=>!n.inert));await page.locator('[data-action="close-reading"]').click();await Q.screenshot(ctx,'interaction-viewport-'+w);}
});
