const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const recipe=path.join(__dirname,'../starter/js/recipes/chemistry-bridge.js');
test('chemistry bridge exposes a reusable authored lesson',()=>{assert.ok(fs.existsSync(recipe),'chemistry bridge recipe must exist');});
function setup(){const dom=new JSDOM('<main id="frame"></main>',{runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,scenes=[],jobs=[];
 for(const f of ['lib/dom.js','lib/i18n.js','lesson.js','interaction-regions.js','film.js','layout.js','molecular.js','molecular-regulation.js','molecular-inspect.js','chemistry.js','physical-chemistry.js'])w.eval(fs.readFileSync(path.join(__dirname,'../starter/js',f),'utf8'));
 w.D.deck={register(c){scenes.push(c);},count(){return 16;}};w.A={run(fn){let resolve;const promise=new Promise(r=>resolve=r);jobs.push({fn,resolve});return promise;}};
 for(const f of ['chemistry-foundations-bonds.js','chemistry-foundations-environment.js','chemistry-foundations-transfer.js','chemistry-context-binding.js','chemistry-context-reactions.js','chemistry-context-transport.js','chemistry-context-energy.js','chemistry-bridge.js','chemistry-physics-scenes.js'])w.eval(fs.readFileSync(path.join(__dirname,'../starter/js/recipes',f),'utf8'));return {w,scenes,jobs};}
test('displayed negative energies retain their sign and only rounded negative zero is normalized',()=>{const {w}=setup();assert.equal(w.CHEMISTRY_BRIDGE.H.fmt(-.1816),'-0.18');assert.equal(w.CHEMISTRY_BRIDGE.H.fmt(-.0001),'0.00');w.close();});
test('reaction conserves atoms and charge while bent water and linear CO2 retain distinct dipoles',()=>{const {w}=setup(),svg=w.document.createElementNS('http://www.w3.org/2000/svg','svg');w.document.querySelector('main').append(svg);const find=id=>w.CHEMISTRY_BRIDGE.createSpecimen({svg},w.CHEMISTRY_BRIDGE.specimens.find(s=>s.id===id));const reaction=find('reaction');for(const p of [0,.42,.67,.73,.74,.75,.84,1]){reaction.paint(p);assert.deepEqual(JSON.parse(JSON.stringify(reaction.metrics.atoms)),{N:1,H:5,O:1});assert.equal(reaction.metrics.totalCharge,0);}const dipole=find('polarity');dipole.paint(1);assert.equal(dipole.metrics.waterAngle,104.5);assert.equal(dipole.metrics.co2Angle,180);assert.ok(dipole.metrics.waterDipolePixels>0);assert.equal(dipole.metrics.co2DipolePixels,0);const occ=find('occupancy');occ.paint(.7);assert.equal(occ.metrics.theta,.5);const methyl=find('histone');methyl.paint(1);assert.equal(methyl.metrics.nitrogenCharge,1);w.close();});
test('sixteen source-linked bilingual scenes keep shape identity through arbitrary scrubbing',()=>{const {w,scenes}=setup();assert.equal(scenes.length,16);assert.equal(new Set(scenes.map(s=>s.id)).size,16);
 for(const spec of w.CHEMISTRY_BRIDGE.specimens){assert.match(spec.url,/^https:\/\//);assert.ok(spec.enTitle&&spec.enNote&&spec.enAnswer);const svg=w.document.createElementNS('http://www.w3.org/2000/svg','svg');w.document.querySelector('main').append(svg);const a=w.CHEMISTRY_BRIDGE.createSpecimen({svg},spec);a.paint(0);const shapes=()=>[...a.g.querySelectorAll('g,path,line,circle,ellipse,rect,polygon')],initial=shapes(),start=JSON.stringify(a.metrics);
  for(const p of [1,.23,.5,.77,.02,.99,0]){a.paint(p);assert.deepEqual(shapes(),initial,spec.id+' stable shapes');assert.ok(!a.g.outerHTML.includes('NaN'),spec.id+' finite geometry');}
  assert.equal(JSON.stringify(a.metrics),start,spec.id+' restored model');assert.throws(()=>a.paint(NaN));}
});
test('manual scrub, inspection and disposal cancel pending chemistry animation',async()=>{const {w,scenes,jobs}=setup(),dispose=[];const root=scenes[1].build({index:1,onDispose(fn){dispose.push(fn);},step(){throw Error('No hidden steps');}});w.document.querySelector('main').append(root);const play=root.querySelector('[data-vlk-button$="-play"]');play.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));jobs[0].fn(.25);const input=root.querySelector('input[type=range]');input.value='60';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(+root.dataset.progress,.6);jobs[0].fn(.9);jobs[0].resolve();await Promise.resolve();assert.equal(+root.dataset.progress,.6);
 play.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));jobs[1].fn(.2);root.querySelector('[data-molecular-inspect]').dispatchEvent(new w.MouseEvent('click',{bubbles:true}));const frozen=root.dataset.progress;jobs[1].fn(.9);jobs[1].resolve();await Promise.resolve();assert.equal(root.dataset.progress,frozen);assert.ok(w.document.querySelector('[data-molecular-detail]'));w.document.querySelector('[data-molecular-detail] button').click();play.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));jobs[2].fn(.2);dispose.reverse().forEach(fn=>fn());const last=root.dataset.progress;jobs[2].fn(.9);jobs[2].resolve();await Promise.resolve();assert.equal(root.dataset.progress,last);assert.equal(w.document.querySelector('[data-molecular-detail]'),null);});
