/* Regression: manual controls must keep visible evidence and narration consistent. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),test=require('node:test');
const {JSDOM}=require('jsdom');
const root=process.env.LESSON_TEST_DIR||path.join(__dirname,'..','starter');
function scene(t){const dom=new JSDOM('<body></body>',{runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:false});for(const f of ['lib/dom','lib/num','lib/anim','lib/plot','lib/svg','lesson','film','patterns','inquiry'])w.eval(fs.readFileSync(path.join(root,'js',f+'.js'),'utf8'));let spec;w.D.deck={count:()=>1,register:s=>spec=s};w.eval(fs.readFileSync(path.join(root,'js/episodes/05-ponder.js'),'utf8'));const steps=[],el=spec.build({index:0,step:f=>steps.push(f)});w.document.body.append(el);w.A.setInstant(true);t.after(()=>w.close());return{w,el,steps,buttons:[...el.querySelectorAll('.kit-ponder-controls button')],caption:()=>el.querySelector('.film-caption').textContent};}
function visibleEvidence(el){const points=[...el.querySelectorAll('circle[data-value]')];assert.equal(points.length,6);assert(points.every(n=>n.style.opacity==='1'),'all six observations must be visible');const intervals=[...el.querySelectorAll('line')].filter(n=>n.getAttribute('stroke')===el.ownerDocument.defaultView.C.teal&&n.getAttribute('stroke-width')==='3');assert.equal(intervals.length,2);assert(intervals.every(n=>n.style.opacity==='1'&&n.getAttribute('y1')!==n.getAttribute('y2')),'both observed ranges must be visible');}
test('Manual answer opens evidence and describes the actual visible state',t=>{const{el,buttons,caption}=scene(t);buttons[1].click();visibleEvidence(el);assert.equal(el.querySelector('.kit-ponder-answer').hidden,false);assert.match(caption(),/Одинаковое среднее допускает разный разброс/);assert.doesNotMatch(caption(),/Известно только одно число/);buttons[1].click();visibleEvidence(el);assert.equal(el.querySelector('.kit-ponder-answer').hidden,true);assert.match(caption(),/наблюдения.*диапазоны/i);});
test('Manual hint makes the referenced extremes visible before inviting comparison',t=>{const{el,buttons,caption}=scene(t);buttons[0].click();visibleEvidence(el);assert.equal(el.querySelector('.kit-ponder-hint').hidden,false);assert.equal(el.querySelector('.kit-ponder-answer').hidden,true);assert.match(caption(),/Сравните крайние значения/);buttons[0].click();visibleEvidence(el);assert.match(caption(),/наблюдения.*диапазоны/i);});
test('Normal scripted captions keep their sequence',async t=>{const{el,steps,caption}=scene(t);assert.match(caption(),/Известно только одно число/);await steps[0]();assert.equal(caption(),'Откроем наблюдения на общей шкале и проверим первоначальную догадку.');await steps[1]();assert.equal(caption(),'Сравните крайние значения, сохраняя все точки перед глазами.');await steps[2]();assert.equal(caption(),'Одинаковое среднее допускает разный разброс. Сводка не заменяет наблюдения.');visibleEvidence(el);});
