(function(){
'use strict';const R=RNA;
R.register({id:'rna-ml',title:['Из химии — к задачам машинного обучения','From chemistry to machine learning tasks'],source:['Shen et al., 2024 · RhoFold+','https://www.nature.com/articles/s41592-024-02487-0'],states:[
 ['Задачи отличаются типом ответа: признаки, пары или координаты.','The tasks differ in their output: features, pairs or coordinates.','Четыре основных символа A, C, G, U задают последовательность РНК. Реальная РНК может содержать модифицированные нуклеотиды, но языковые модели часто используют базовый алфавит. Задача представления, задача пар и задача координат — разные выходы. Пустые векторы, знакомая учебная матрица и условная 3D-шпилька иллюстрируют форматы: ни одна модель здесь не запускалась; это не её реальные предсказания.','The four main symbols A, C, G and U define an RNA sequence. Real RNA can contain modified nucleotides, although language models often use a basic alphabet. Representations, pair maps and coordinates are distinct outputs. Empty vectors, the familiar toy matrix and a schematic 3D hairpin illustrate formats: no model was run here, and these are not actual predictions.'],
 ['RNA-FM даёт представления; UFold предсказывает матрицу пар.','RNA-FM produces representations; UFold predicts a base-pair matrix.','RNA-FM обучается на последовательностях и создаёт контекстные представления. Другие модели могут использовать их в структурных задачах. UFold — отдельный метод: он строит попарные признаки и предсказывает карту пар с помощью свёрточной U-Net. Это не обязательная цепочка RNA-FM → UFold.','RNA-FM learns from sequences and produces contextual representations that other models can use for structural tasks. UFold is a separate method: it builds pairwise features and predicts a pair map using a convolutional U-Net. RNA-FM → UFold is not a mandatory pipeline.'],
 ['RhoFold+ использует RNA-FM и выравнивание родственных РНК — MSA.','RhoFold+ uses RNA-FM and an alignment of related RNAs — an MSA.','RhoFold+ — пример end-to-end предсказания пространственной структуры отдельных цепей РНК. Стандартный опубликованный конвейер использует контекстные представления RNA-FM и множественное выравнивание родственных последовательностей (MSA). MSA строится отдельно, а не выдаётся языковой моделью. 2D-матрица полезна как цель или ограничение, но не задаёт 3D однозначно. Доступность и разнообразие структурных данных ограничивают обучение; перенос на новые семейства требует отдельной проверки.','RhoFold+ is an end-to-end predictor of single-chain RNA structures. Its standard published pipeline uses contextual RNA-FM representations and a multiple sequence alignment (MSA) of related sequences. The MSA is constructed separately, not produced by the language model. A 2D matrix is useful as a target or constraint, but it does not uniquely determine 3D geometry. The availability and diversity of structural data constrain training; transfer to new families needs separate evaluation.']
],qa:[{q:['Как проверить, что модель переносится на новые РНК?','How can generalization to new RNAs be tested?'],a:['Нужны отдельные тестовые семейства или структурно отличающиеся примеры. Сходные последовательности и структуры в обучении и тесте могут завысить оценку; хорошая средняя точность не гарантирует правильность конкретного предсказания.','Use held-out families or structurally distinct examples. Similar sequences and structures in training and test sets can inflate performance; good average accuracy does not guarantee a particular prediction is correct.']},{q:['UFold читает пары прямо из attention RNA-FM?','Does UFold read pairs directly from RNA-FM attention?'],a:['Нет. UFold — отдельная свёрточная модель U-Net. RNA-FM даёт контекстные представления, которые могут использовать другие модели.','No. UFold is a separate convolutional U-Net model. RNA-FM produces contextual representations that other models can use.'],source:'Fu et al., 2022 · UFold',url:'https://academic.oup.com/nar/article/50/3/e14/6430845'},{q:['Матрица пар однозначно задаёт все координаты?','Does a pair matrix uniquely determine all coordinates?'],a:['Нет. Нужны взаимная ориентация спиралей, геометрия петель, дальние контакты и дополнительные ограничения.','No. Relative helix orientation, loop geometry, long-range contacts and additional constraints are needed.']}],build(ctx,v){
 const state={tasks:0,three:0};
 R.box(v.svg,76,148,260,47,'Последовательность','Sequence',25,C.grey);
 R.box(v.svg,400,148,475,47,'A C G U …','A C G U …',32,C.white);
 R.box(v.svg,922,148,282,47,'Схемы выходов','Output schematics',25,C.grey);
 const xs=[83,466,849],colors=[C.blue,C.gold,C.teal];
 F.line(v.svg,257,215,1023,215,C.grey,1);F.line(v.svg,640,197,640,215,C.grey,1);
 const kinds=[['Признаки позиции','Features per position'],['Кто с кем в паре?','Which positions pair?'],['Где атомы в 3D?','Where are atoms in 3D?']];
 xs.forEach((x,i)=>{const arrow=F.arrow(v.svg,colors[i],1.5);arrow.set(x+174,215,x+174,239);R.box(v.svg,x,248,348,47,...kinds[i],27,colors[i]);});
 F.line(v.svg,449,268,449,600,C.grey,.8);F.line(v.svg,832,268,832,600,C.grey,.8);
 const features=F.group(v.svg);
 ['A','C','G','U'].forEach((letter,i)=>{R.label(features,121,331+i*36,letter,21,C.blue,32,32);R.label(features,383,331+i*36,'h'+['₁','₂','₃','₄'][i],23,C.blue,40,34);for(let j=0;j<6;j++){const n=R.rect(features,155+j*31,318+i*36,24,24,C.blue,'none',3);n.setAttribute('opacity',.55);}});
 R.box(features,100,464,311,38,'Признаки в контексте','Features in context',22,C.grey);
 const matrix=F.group(v.svg),pairs=[[0,9],[1,8],[4,13],[5,12]],cell=10.5;
 for(let i=0;i<14;i++)for(let j=0;j<14;j++){const on=pairs.some(([a,b])=>a===i&&b===j||a===j&&b===i);const n=R.rect(matrix,566+j*cell,314+i*cell,cell-1,cell-1,on?C.gold:C.grey,on?C.gold:'none',0);n.setAttribute('stroke-width',.55);if(!on)n.setAttribute('opacity',.32);}
 R.box(matrix,481,464,318,38,'Знакомая карта четырёх пар','The familiar four-pair map',22,C.grey);
 // A schematic 13-point helix uses the same glyph as the geometry bridge.
 // It illustrates the type of output; no model inference is being displayed.
 const spatial=F.group(v.svg),xyz=Array.from({length:13},()=>[0,0,0]);
 for(let i=0;i<5;i++){const t=i*.56;xyz[i]=[-15*Math.cos(t),45-i*20,-15*Math.sin(t)];xyz[12-i]=[15*Math.cos(t),45-i*20,15*Math.sin(t)];}xyz[5]=[-17,-58,-2];xyz[6]=[0,-71,0];xyz[7]=[17,-58,2];
 const trace=F.path(spatial,[],C.teal,2.6),dots=xyz.map(()=>F.dot(spatial,0,0,3.4,C.teal));
 const axes=F.group(spatial);[[[921,436],[976,436],'x',982,436],[[921,436],[921,379],'y',920,365],[[921,436],[888,455],'z',873,460]].forEach(([a,b,t,x,y])=>{const ar=F.arrow(axes,C.grey,1);ar.set(...a,...b);R.label(axes,x,y,t,17,C.grey,26,28);});
 R.box(spatial,1036,332,162,83,'(xᵢ, yᵢ, zᵢ)','(xᵢ, yᵢ, zᵢ)',25,C.teal);
 R.box(spatial,870,464,313,38,'Геометрия · схема выхода','Geometry · schematic output',22,C.grey);
 const names=F.group(v.svg),three=F.group(v.svg);
 R.box(names,91,519,334,44,'RNA-FM','RNA-FM',31,C.blue);
 R.box(names,474,519,334,44,'UFold · U-Net','UFold · U-Net',30,C.gold);
 R.box(names,91,564,334,39,'Векторы признаков hᵢ','Feature vectors hᵢ',23,C.grey);
 R.box(names,474,564,334,39,'Отдельная модель пар','A separate pair predictor',23,C.grey);
 R.box(three,858,519,342,44,'RhoFold+','RhoFold+',31,C.teal);
 R.box(three,858,562,342,42,'RNA-FM + родственные РНК','RNA-FM + related RNAs',22,C.grey);
 function paint(){F.opacity(names,state.tasks);F.opacity(three,state.three);const angle=.25+state.three*.55;const pts=xyz.map(([x,y,z])=>[997+(x*Math.cos(angle)+z*Math.sin(angle))*1.07,399+y*1.07]);trace.setAttribute('d',pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(' '));dots.forEach((n,i)=>F.pos(n,...pts[i]));}
 return{state,paint,patches:[{tasks:1},{three:1}],durations:[1000,1600]};
}});

R.register({id:'rna-takeaways',title:['Проверьте концепт: пары, форма, условия','Check the concept: pairs, shape, conditions'],source:['Shelton et al., 2001 · Takamoto et al., 2004 · Shen et al., 2024','https://pubmed.ncbi.nlm.nih.gov/11297430/'],states:[
 ['Три вопроса: сначала сформулируйте собственный ответ.','Three questions: give your own answers first.','Используйте следующий шаг для раскрытия каждого ответа. Смысл урока: вторичная структура — удобный каркас рассуждения о РНК, но форма зависит от геометрии, среды и взаимодействий между элементами.','Use the next step to reveal each answer. The lesson’s central point is that secondary structure provides a useful framework for reasoning about RNA, while shape depends on geometry, environment and interactions between elements.'],
 ['Одна схема пар допускает разные пространственные расположения.','One pairing pattern permits different spatial arrangements.','Вторичная структура фиксирует отношения между нуклеотидами. Она не определяет однозначно ориентацию всех стеблей, петли и дальние контакты в пространстве.','Secondary structure specifies relations between nucleotides. It does not uniquely determine every helix orientation, loop conformation and long-range spatial contact.'],
 ['Ионы помогают экранировать заряд; роль Mg²⁺ зависит от РНК и условий.','Ions help screen charge; the role of Mg²⁺ depends on RNA and conditions.','Нельзя объявить Mg²⁺ универсально обязательным для любой 3D-укладки. Он эффективно стабилизирует многие структуры, иногда участвуя в специфических контактах. Одновалентные ионы тоже влияют на укладку.','Mg²⁺ cannot be declared universally mandatory for every 3D fold. It efficiently stabilizes many structures, sometimes through specific contacts. Monovalent ions also influence folding.'],
 ['Иерархия помогает объяснять РНК, но не задаёт единственный путь фолдинга.','Hierarchy helps explain RNA, but does not prescribe a single folding pathway.','Сохраняйте три различия: последовательность не равна схеме пар; схема пар не равна координатам; авторская анимация не равна физической траектории. Локальная и глобальная укладка могут быть сопряжены.','Keep three distinctions: a sequence is not a pair map; a pair map is not coordinates; an authored animation is not a physical trajectory. Local and global folding can be coupled.']
],qa:[{q:['Как объяснить отличие РНК одной фразой?','How can the RNA distinction be explained in one sentence?'],a:['РНК удобно понимать как заряженную цепь, где пары и стэкинг создают локальный каркас, а дальние контакты и ионная среда помогают организовать его в 3D.','RNA can be understood as a charged chain in which pairing and stacking create a local framework, while long-range contacts and the ionic environment help organize it in 3D.']},{q:['Какие три упрощения стоит избегать?','Which three oversimplifications should be avoided?'],a:['«Всегда строго по этапам», «Mg²⁺ обязателен для любой РНК» и «матрица пар полностью определяет 3D».','“Always in strict stages,” “Mg²⁺ is mandatory for every RNA,” and “a pair matrix completely determines 3D.”']}],build(ctx,v){
 const state={a:0,b:0,c:0};
 const content=[['Чего не хватает карте пар?','What is missing from a pair map?','Ориентаций стеблей\nи дальних контактов','Helix orientations\nand long-range contacts'],['Зачем РНК ионы?','Why does RNA need ions?','Они экранируют заряд.\nВажны состав и условия.','They screen charge.\nConditions matter.'],['Почему важен путь?','Why does the pathway matter?','Новые партнёры\nпоявляются при синтезе.','New partners appear\nas the chain is synthesized.']];
 const answers=content.map((s,i)=>{const x=79+i*394;R.box(v.svg,x,173,337,85,s[0],s[1],29,C.white);F.line(v.svg,x+30,475,x+306,475,C.grey,1);return R.box(v.svg,x,502,337,92,s[2],s[3],25,C.gold);});
 const first=F.group(v.svg);R.helix(first,{x:165,y:359,length:111,width:35,angle:-25,color:C.blue,levels:4});const movable=R.helix(first,{x:308,y:359,length:111,width:35,angle:34,color:C.teal,levels:4});
 const connector=R.path(first,'',C.grey,2);
 const ions=F.group(v.svg),h=R.chain(ions,R.seq,R.hairpinPoints(641,360,.4),R.pairs,4,C.blue);h.nodes.forEach(n=>n.querySelector('text').setAttribute('opacity',0));h.set(R.hairpinPoints(641,360,.4),1);
 const cloud=[];for(let i=0;i<14;i++){const a=i*2.39996,r=65+(i%3)*10;cloud.push(F.dot(ions,641+Math.cos(a)*r,354+Math.sin(a)*r,3.6,C.gold));}R.label(ions,582,341,'−',20,C.blue,27,30);R.label(ions,682,389,'−',20,C.blue,27,30);
 const chain=F.group(v.svg),newPart=F.group(chain);[0,1,2,3,4,5].forEach(i=>{const parent=i<3?chain:newPart;if(i)F.line(parent,917+(i-1)*40,354,917+i*40,354,C.blue,2);F.dot(parent,917+i*40,354,8,C.blue);});const arrow=F.arrow(chain,C.grey,1.5);arrow.set(920,407,1122,407);R.box(chain,925,423,186,30,'Синтез 5′ → 3′','Synthesis 5′ → 3′',19,C.grey);
 function paint(){answers.forEach((a,i)=>F.opacity(a.el,state[['a','b','c'][i]]));const angle=34-state.a*48;movable.set({angle});const a=angle*Math.PI/180,ax=165+17.5*Math.cos(-25*Math.PI/180)-55.5*Math.sin(-25*Math.PI/180),ay=359+17.5*Math.sin(-25*Math.PI/180)+55.5*Math.cos(-25*Math.PI/180),bx=308-17.5*Math.cos(a)-55.5*Math.sin(a),by=359-17.5*Math.sin(a)+55.5*Math.cos(a);connector.setAttribute('d',`M${ax} ${ay} Q240 451 ${bx} ${by}`);cloud.forEach(n=>F.opacity(n,.2+state.b*.8));F.opacity(newPart,.15+state.c*.85);}
 return{state,paint,patches:[{a:1},{b:1},{c:1}],durations:[1500,1100,1200]};
}});
})();
