// Generated by build/trna-data.py from supplied PDB 1EHZ assets.
// Keep component identity and indices across every representation.
window.TRNA_DATA = {
  "schemaVersion": 1,
  "pdbId": "1EHZ",
  "chain": "A",
  "model": 1,
  "sourceURL": "https://files.rcsb.org/download/1EHZ.cif",
  "entryURL": "https://www.rcsb.org/structure/1EHZ",
  "primaryPaperURL": "https://pmc.ncbi.nlm.nih.gov/articles/PMC1369984/",
  "sourceHash": "3021dd2b6461f850bb66d6748d3c22a5e1bb6cc891c625c15d793f38215b28ab",
  "method": "X-RAY DIFFRACTION",
  "resolutionAngstrom": 1.93,
  "organism": "Saccharomyces cerevisiae",
  "units": "angstrom",
  "selectedAtom": "C4'",
  "sequence": "GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA",
  "residues": [
    {
      "id": 1,
      "component": "G",
      "base": "G",
      "xyz": [
        50.968,
        49.231,
        54.309
      ]
    },
    {
      "id": 2,
      "component": "C",
      "base": "C",
      "xyz": [
        56.836,
        48.075,
        56.049
      ]
    },
    {
      "id": 3,
      "component": "G",
      "base": "G",
      "xyz": [
        62.769,
        46.443,
        54.422
      ]
    },
    {
      "id": 4,
      "component": "G",
      "base": "G",
      "xyz": [
        66.749,
        44.634,
        50.114
      ]
    },
    {
      "id": 5,
      "component": "A",
      "base": "A",
      "xyz": [
        67.927,
        42.844,
        44.191
      ]
    },
    {
      "id": 6,
      "component": "U",
      "base": "U",
      "xyz": [
        66.579,
        44.4,
        38.565
      ]
    },
    {
      "id": 7,
      "component": "U",
      "base": "U",
      "xyz": [
        64.055,
        47.852,
        34.101
      ]
    },
    {
      "id": 8,
      "component": "U",
      "base": "U",
      "xyz": [
        66.105,
        52.236,
        29.628
      ]
    },
    {
      "id": 9,
      "component": "A",
      "base": "A",
      "xyz": [
        64.531,
        52.215,
        22.904
      ]
    },
    {
      "id": 10,
      "component": "2MG",
      "base": "G",
      "xyz": [
        59.058,
        48.375,
        20.709
      ]
    },
    {
      "id": 11,
      "component": "C",
      "base": "C",
      "xyz": [
        60.091,
        42.608,
        23.221
      ]
    },
    {
      "id": 12,
      "component": "U",
      "base": "U",
      "xyz": [
        64.121,
        39.544,
        26.594
      ]
    },
    {
      "id": 13,
      "component": "C",
      "base": "C",
      "xyz": [
        69.102,
        41.516,
        29.762
      ]
    },
    {
      "id": 14,
      "component": "A",
      "base": "A",
      "xyz": [
        74.612,
        43.815,
        30.626
      ]
    },
    {
      "id": 15,
      "component": "G",
      "base": "G",
      "xyz": [
        78.274,
        48.248,
        31.867
      ]
    },
    {
      "id": 16,
      "component": "H2U",
      "base": "U",
      "xyz": [
        80.514,
        52.486,
        33.353
      ]
    },
    {
      "id": 17,
      "component": "H2U",
      "base": "U",
      "xyz": [
        84.176,
        55.886,
        36.15
      ]
    },
    {
      "id": 18,
      "component": "G",
      "base": "G",
      "xyz": [
        80.1,
        59.412,
        35.902
      ]
    },
    {
      "id": 19,
      "component": "G",
      "base": "G",
      "xyz": [
        80.105,
        62.508,
        30.407
      ]
    },
    {
      "id": 20,
      "component": "G",
      "base": "G",
      "xyz": [
        80.529,
        60.879,
        23.849
      ]
    },
    {
      "id": 21,
      "component": "A",
      "base": "A",
      "xyz": [
        75.622,
        58.001,
        23.58
      ]
    },
    {
      "id": 22,
      "component": "G",
      "base": "G",
      "xyz": [
        76.292,
        51.916,
        21.581
      ]
    },
    {
      "id": 23,
      "component": "A",
      "base": "A",
      "xyz": [
        76.705,
        45.975,
        20.257
      ]
    },
    {
      "id": 24,
      "component": "G",
      "base": "G",
      "xyz": [
        74.313,
        40.622,
        18.747
      ]
    },
    {
      "id": 25,
      "component": "C",
      "base": "C",
      "xyz": [
        69.17,
        38.275,
        16.491
      ]
    },
    {
      "id": 26,
      "component": "M2G",
      "base": "G",
      "xyz": [
        63.938,
        40.267,
        14.143
      ]
    },
    {
      "id": 27,
      "component": "C",
      "base": "C",
      "xyz": [
        61.594,
        44.378,
        10.321
      ]
    },
    {
      "id": 28,
      "component": "C",
      "base": "C",
      "xyz": [
        62.918,
        48.099,
        5.246
      ]
    },
    {
      "id": 29,
      "component": "A",
      "base": "A",
      "xyz": [
        67.384,
        49.009,
        1.027
      ]
    },
    {
      "id": 30,
      "component": "G",
      "base": "G",
      "xyz": [
        72.933,
        47.996,
        -1.281
      ]
    },
    {
      "id": 31,
      "component": "A",
      "base": "A",
      "xyz": [
        77.346,
        43.848,
        -2.3
      ]
    },
    {
      "id": 32,
      "component": "OMC",
      "base": "C",
      "xyz": [
        77.712,
        38.038,
        -3.579
      ]
    },
    {
      "id": 33,
      "component": "U",
      "base": "U",
      "xyz": [
        74.457,
        33.095,
        -5.87
      ]
    },
    {
      "id": 34,
      "component": "OMG",
      "base": "G",
      "xyz": [
        70.295,
        33.326,
        -11.163
      ]
    },
    {
      "id": 35,
      "component": "A",
      "base": "A",
      "xyz": [
        65.999,
        34.348,
        -7.216
      ]
    },
    {
      "id": 36,
      "component": "A",
      "base": "A",
      "xyz": [
        65.801,
        33.698,
        -1.565
      ]
    },
    {
      "id": 37,
      "component": "YYG",
      "base": "G",
      "xyz": [
        66.976,
        32.279,
        4.107
      ]
    },
    {
      "id": 38,
      "component": "A",
      "base": "A",
      "xyz": [
        71.783,
        31.31,
        7.804
      ]
    },
    {
      "id": 39,
      "component": "PSU",
      "base": "U",
      "xyz": [
        77.034,
        33.8,
        8.726
      ]
    },
    {
      "id": 40,
      "component": "5MC",
      "base": "C",
      "xyz": [
        80.351,
        38.97,
        7.985
      ]
    },
    {
      "id": 41,
      "component": "U",
      "base": "U",
      "xyz": [
        80.498,
        45.168,
        6.953
      ]
    },
    {
      "id": 42,
      "component": "G",
      "base": "G",
      "xyz": [
        77.769,
        50.433,
        7.372
      ]
    },
    {
      "id": 43,
      "component": "G",
      "base": "G",
      "xyz": [
        73.059,
        54.264,
        8.204
      ]
    },
    {
      "id": 44,
      "component": "A",
      "base": "A",
      "xyz": [
        67.971,
        56.191,
        10.523
      ]
    },
    {
      "id": 45,
      "component": "G",
      "base": "G",
      "xyz": [
        64.255,
        55.158,
        15.248
      ]
    },
    {
      "id": 46,
      "component": "7MG",
      "base": "G",
      "xyz": [
        63.911,
        55.833,
        21.859
      ]
    },
    {
      "id": 47,
      "component": "U",
      "base": "U",
      "xyz": [
        62.482,
        60.255,
        26.545
      ]
    },
    {
      "id": 48,
      "component": "C",
      "base": "C",
      "xyz": [
        66.046,
        56.424,
        30.251
      ]
    },
    {
      "id": 49,
      "component": "5MC",
      "base": "C",
      "xyz": [
        61.796,
        55.006,
        32.81
      ]
    },
    {
      "id": 50,
      "component": "U",
      "base": "U",
      "xyz": [
        59.218,
        60.444,
        34.331
      ]
    },
    {
      "id": 51,
      "component": "G",
      "base": "G",
      "xyz": [
        59.365,
        65.668,
        37.334
      ]
    },
    {
      "id": 52,
      "component": "U",
      "base": "U",
      "xyz": [
        62.118,
        69.559,
        40.905
      ]
    },
    {
      "id": 53,
      "component": "G",
      "base": "G",
      "xyz": [
        67.174,
        70.724,
        43.912
      ]
    },
    {
      "id": 54,
      "component": "5MU",
      "base": "U",
      "xyz": [
        73.295,
        70.03,
        45.246
      ]
    },
    {
      "id": 55,
      "component": "PSU",
      "base": "U",
      "xyz": [
        78.398,
        70.137,
        41.999
      ]
    },
    {
      "id": 56,
      "component": "C",
      "base": "C",
      "xyz": [
        79.735,
        74.239,
        36.678
      ]
    },
    {
      "id": 57,
      "component": "G",
      "base": "G",
      "xyz": [
        76.829,
        69.964,
        33.385
      ]
    },
    {
      "id": 58,
      "component": "1MA",
      "base": "A",
      "xyz": [
        74.279,
        63.972,
        33.383
      ]
    },
    {
      "id": 59,
      "component": "U",
      "base": "U",
      "xyz": [
        70.618,
        58.472,
        33.026
      ]
    },
    {
      "id": 60,
      "component": "C",
      "base": "C",
      "xyz": [
        73.252,
        56.436,
        38.285
      ]
    },
    {
      "id": 61,
      "component": "C",
      "base": "C",
      "xyz": [
        75.643,
        58.316,
        43.84
      ]
    },
    {
      "id": 62,
      "component": "A",
      "base": "A",
      "xyz": [
        71.882,
        60.684,
        48.244
      ]
    },
    {
      "id": 63,
      "component": "C",
      "base": "C",
      "xyz": [
        66.263,
        61.75,
        50.244
      ]
    },
    {
      "id": 64,
      "component": "A",
      "base": "A",
      "xyz": [
        60.204,
        61.569,
        49.339
      ]
    },
    {
      "id": 65,
      "component": "G",
      "base": "G",
      "xyz": [
        55.988,
        59.17,
        46.06
      ]
    },
    {
      "id": 66,
      "component": "A",
      "base": "A",
      "xyz": [
        53.671,
        55.677,
        41.542
      ]
    },
    {
      "id": 67,
      "component": "A",
      "base": "A",
      "xyz": [
        53.319,
        50.645,
        38.32
      ]
    },
    {
      "id": 68,
      "component": "U",
      "base": "U",
      "xyz": [
        55.168,
        44.94,
        37.012
      ]
    },
    {
      "id": 69,
      "component": "U",
      "base": "U",
      "xyz": [
        57.582,
        39.88,
        39.4
      ]
    },
    {
      "id": 70,
      "component": "C",
      "base": "C",
      "xyz": [
        59.348,
        35.925,
        43.805
      ]
    },
    {
      "id": 71,
      "component": "G",
      "base": "G",
      "xyz": [
        59.688,
        34.434,
        49.701
      ]
    },
    {
      "id": 72,
      "component": "C",
      "base": "C",
      "xyz": [
        57.653,
        35.834,
        55.45
      ]
    },
    {
      "id": 73,
      "component": "A",
      "base": "A",
      "xyz": [
        53.508,
        38.772,
        58.837
      ]
    },
    {
      "id": 74,
      "component": "C",
      "base": "C",
      "xyz": [
        47.463,
        40.541,
        58.985
      ]
    },
    {
      "id": 75,
      "component": "C",
      "base": "C",
      "xyz": [
        42.564,
        38.194,
        56.568
      ]
    },
    {
      "id": 76,
      "component": "A",
      "base": "A",
      "xyz": [
        37.607,
        38.379,
        58.569
      ]
    }
  ],
  "modified": [
    {
      "id": 10,
      "component": "2MG",
      "base": "G"
    },
    {
      "id": 16,
      "component": "H2U",
      "base": "U"
    },
    {
      "id": 17,
      "component": "H2U",
      "base": "U"
    },
    {
      "id": 26,
      "component": "M2G",
      "base": "G"
    },
    {
      "id": 32,
      "component": "OMC",
      "base": "C"
    },
    {
      "id": 34,
      "component": "OMG",
      "base": "G"
    },
    {
      "id": 37,
      "component": "YYG",
      "base": "G"
    },
    {
      "id": 39,
      "component": "PSU",
      "base": "U"
    },
    {
      "id": 40,
      "component": "5MC",
      "base": "C"
    },
    {
      "id": 46,
      "component": "7MG",
      "base": "G"
    },
    {
      "id": 49,
      "component": "5MC",
      "base": "C"
    },
    {
      "id": 54,
      "component": "5MU",
      "base": "U"
    },
    {
      "id": 55,
      "component": "PSU",
      "base": "U"
    },
    {
      "id": 58,
      "component": "1MA",
      "base": "A"
    }
  ],
  "stemPairs": [
    [
      1,
      72
    ],
    [
      2,
      71
    ],
    [
      3,
      70
    ],
    [
      4,
      69
    ],
    [
      5,
      68
    ],
    [
      6,
      67
    ],
    [
      7,
      66
    ],
    [
      10,
      25
    ],
    [
      11,
      24
    ],
    [
      12,
      23
    ],
    [
      13,
      22
    ],
    [
      27,
      43
    ],
    [
      28,
      42
    ],
    [
      29,
      41
    ],
    [
      30,
      40
    ],
    [
      31,
      39
    ],
    [
      49,
      65
    ],
    [
      50,
      64
    ],
    [
      51,
      63
    ],
    [
      52,
      62
    ],
    [
      53,
      61
    ]
  ],
  "anticodon": [
    34,
    35,
    36
  ],
  "cca": [
    74,
    75,
    76
  ],
  "basis": [
    [
      -0.704858062764348,
      -0.41373289261369006,
      0.5761945894622744
    ],
    [
      -0.23042024713417378,
      -0.6346941460188456,
      -0.7376109074031069
    ],
    [
      0.6708812272427337,
      -0.6526778949672779,
      0.35203685084713265
    ]
  ],
  "origin": [
    79.92,
    68.3735,
    33.5425
  ],
  "representationNotes": [
    "ACGU letters identify parent bases; the 14 deposited modifications retain their component IDs.",
    "One C4-prime position per residue forms a coarse trace, not an atomistic chemical-bond graph.",
    "The 21 conventional stem pairs define the authored cloverleaf, not every tertiary contact.",
    "Transitions between sequence, cloverleaf and deposited 3D coordinates show correspondence, not a physical folding trajectory.",
    "G19-C56 is a Watson-Crick tertiary inter-loop pair, distinct from the 21 conventional stem pairs; G18-PSU55 is noncanonical."
  ]
};
